In [1]:
import pandas as pd
import numpy as np
import pandas_ta as ta
import talib
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import math as m
import yfinance as yf
import breeze_connect
from breeze_connect import BreezeConnect

print("Imported necessary libraries")

/home/ganesh/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

Imported necessary libraries

In [2]:
with open('/home/ganesh/Github/markets/token_breeze.md', 'r', encoding='utf-8') as file:
    contents = file.readlines()
    fresh_token = contents[0]
    print(fresh_token)
    print(type(fresh_token))

7928549

<class 'str'>

In [3]:
isec = BreezeConnect(api_key="06890j43os6a521A7b7241i934KQ9S56")
isec.generate_session(
    api_secret="$42367K2z98758S712349896J6i^64Mx",
    session_token=fresh_token)

# Get option chain quotes  

> Enter two of the following to get option chain in different formats  
    >> expiry_date  
    >> right  
    >> strike_price

## Using expiry_date and right

In [5]:
oc = isec.get_option_chain_quotes(stock_code="NIFTY",
                    exchange_code="NFO",
                    product_type="options",
                    expiry_date="2023-04-13T06:00:00.000Z",
                    right="call")
ocdf = pd.DataFrame(oc["Success"])
ocdf

,exchange_code,product_type,stock_code,expiry_date,right,strike_price,ltp,ltt,best_bid_price,best_bid_quantity,...,ltp_percent_change,upper_circuit,lower_circuit,total_quantity_traded,spot_price,ltq,open_interest,chnge_oi,total_buy_qty,total_sell_qty
0,NFO,Options,NIFTY,13-Apr-2023,Call,13950.0,0.0,,0.0,0,...,0.0,4463.85,3091.65,0,17812.4,0,0.0,0.0,0,0
1,NFO,Options,NIFTY,13-Apr-2023,Call,14000.0,0.0,,0.0,0,...,0.0,4413.85,3041.65,0,17812.4,0,0.0,0.0,0,0
2,NFO,Options,NIFTY,13-Apr-2023,Call,14050.0,0.0,,0.0,0,...,0.0,4363.85,2991.65,0,17812.4,0,0.0,0.0,0,0
3,NFO,Options,NIFTY,13-Apr-2023,Call,14100.0,0.0,,0.0,0,...,0.0,4313.90,2941.70,0,17812.4,0,0.0,0.0,0,0
4,NFO,Options,NIFTY,13-Apr-2023,Call,14150.0,0.0,,0.0,0,...,0.0,4327.95,2891.70,0,17812.4,0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,NFO,Options,NIFTY,13-Apr-2023,Call,20600.0,0.0,,0.0,0,...,0.0,3.05,0.05,0,17812.4,0,0.0,0.0,0,0
134,NFO,Options,NIFTY,13-Apr-2023,Call,20650.0,0.0,,0.0,0,...,0.0,7.20,0.05,0,17812.4,0,0.0,0.0,0,0
135,NFO,Options,NIFTY,13-Apr-2023,Call,20700.0,0.0,,0.0,0,...,0.0,7.10,0.05,0,17812.4,0,0.0,0.0,0,0
136,NFO,Options,NIFTY,13-Apr-2023,Call,20750.0,0.0,,0.0,0,...,0.0,0.00,0.00,0,17812.4,0,0.0,0.0,0,0
137,NFO,Options,NIFTY,13-Apr-2023,Call,20800.0,0.0,,0.0,0,...,0.0,0.00,0.00,0,17812.4,0,0.0,0.0,0,0

## Using expiry_date and strike_price

In [6]:
oc2 = isec.get_option_chain_quotes(stock_code="NIFTY",
                    exchange_code="NFO",
                    product_type="options",
                    expiry_date="2023-04-13T06:00:00.000Z",
                    strike_price="17800")
ocdf2 = pd.DataFrame(oc2["Success"])
ocdf2.head()

,exchange_code,product_type,stock_code,expiry_date,right,strike_price,ltp,ltt,best_bid_price,best_bid_quantity,...,ltp_percent_change,upper_circuit,lower_circuit,total_quantity_traded,spot_price,ltq,open_interest,chnge_oi,total_buy_qty,total_sell_qty
0,NFO,Options,NIFTY,13-Apr-2023,Call,17800.0,53.00,12-Apr-2023 15:29:59,52.4,100,...,116.77,434.4,0.05,404940050,17812.4,250,8723550.0,1250800.0,871850,565900
1,NFO,Options,NIFTY,13-Apr-2023,Put,17800.0,41.05,12-Apr-2023 15:29:59,41.1,650,...,-55.28,511.7,0.05,298110900,17812.4,50,7598050.0,5714350.0,499000,910750

## Using right and strike_price

In [7]:
oc3 = isec.get_option_chain_quotes(stock_code="NIFTY",
                    exchange_code="NFO",
                    product_type="options",
                    right="call",
                    strike_price="17800")
ocdf3 = pd.DataFrame(oc3["Success"])
ocdf3

,exchange_code,product_type,stock_code,expiry_date,right,strike_price,ltp,ltt,best_bid_price,best_bid_quantity,...,ltp_percent_change,upper_circuit,lower_circuit,total_quantity_traded,spot_price,ltq,open_interest,chnge_oi,total_buy_qty,total_sell_qty
0,NFO,Options,NIFTY,13-Apr-2023,Call,17800.0,53.00,12-Apr-2023 15:29:59,52.40,100,...,116.77,434.40,0.05,404940050,17812.4,250,8723550.0,1250800.0,871850,565900
1,NFO,Options,NIFTY,20-Apr-2023,Call,17800.0,122.00,12-Apr-2023 15:29:59,122.00,1100,...,46.55,498.80,0.05,11899350,17812.4,100,1434950.0,594300.0,57200,40700
2,NFO,Options,NIFTY,27-Apr-2023,Call,17800.0,183.00,12-Apr-2023 15:29:58,182.95,300,...,29.06,563.55,0.05,5831050,17812.4,50,2319950.0,314550.0,59200,32350
3,NFO,Options,NIFTY,04-May-2023,Call,17800.0,232.50,12-Apr-2023 15:29:52,230.20,50,...,23.54,615.30,0.05,53200,17812.4,50,18300.0,-2350.0,17700,6950
4,NFO,Options,NIFTY,11-May-2023,Call,17800.0,275.00,12-Apr-2023 15:27:48,267.35,150,...,-20.49,571.15,20.70,1300,17812.4,100,800.0,0.0,6550,4050
5,NFO,Options,NIFTY,25-May-2023,Call,17800.0,338.05,12-Apr-2023 15:29:53,336.15,50,...,15.24,733.40,0.05,260100,17812.4,50,325000.0,26700.0,8450,6050
6,NFO,Options,NIFTY,29-Jun-2023,Call,17800.0,476.15,12-Apr-2023 15:27:15,470.35,100,...,11.93,881.75,35.00,37050,17812.4,100,34250.0,18450.0,3450,4450