In [1]:
import nsepy

In [3]:
from nsepy import get_history
from datetime import datetime

`Getting stock data`

In [14]:
symbol = 'SBIN'

start = datetime(2022, 1, 1)
end = datetime.now()

sbin = get_history(symbol=symbol, 
                    start=start, 
                    end=end,)
sbin.tail()

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2022-08-12,SBIN,EQ,524.75,525.70,531.80,525.15,531.00,530.70,529.76,12154012,6.438751e+14,160036,5679718,0.4673
2022-08-16,SBIN,EQ,530.70,533.30,533.85,525.00,526.60,525.95,527.74,10721167,5.657980e+14,145707,5025077,0.4687
2022-08-17,SBIN,EQ,525.95,528.85,530.55,524.35,527.80,528.15,526.89,12054183,6.351246e+14,159055,5203847,0.4317
2022-08-18,SBIN,EQ,528.15,526.85,534.80,526.20,532.00,532.35,531.57,9013662,4.791386e+14,120443,2772894,0.3076
2022-08-19,SBIN,EQ,532.35,532.00,533.65,518.50,520.05,520.35,523.18,11087222,5.800623e+14,146387,4095463,0.3694

`Getting F&O data`

In [20]:
exp = datetime(2022,8,25)

nifty_fut = get_history(symbol="NIFTY",
                        start=exp,
                        end=exp,
                        index=True,
                        futures=True,
                        expiry_date=exp)
nifty_fut.tail()

Empty DataFrame
Columns: [Symbol, Expiry, Open, High, Low, Close, Last, Settle Price, Number of Contracts, Turnover, Open Interest, Change in OI, Underlying]
Index: []

In [21]:
exp = datetime(2022,8,25)

nifty_opt = get_history(symbol="NIFTY",
                        start=exp,
                        end=exp,
                        index=True,
                        option_type='CE',
                        strike_price=18000,
                        expiry_date=exp)
nifty_opt.tail()

Empty DataFrame
Columns: [Symbol, Expiry, Option Type, Strike Price, Open, High, Low, Close, Last, Settle Price, Number of Contracts, Turnover, Premium Turnover, Open Interest, Change in OI, Underlying]
Index: []